# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"
  messenger: true
  twig:
    mode: lazy
  resolvers:
    default:
      web_path: ~
  filter_sets:
    cache: ~
    small_thumb:
      quality: 75
      filters:
        auto_rotate: ~ # for some reason if you don't set auto_rotate explicitly it rotates everything to the left
        thumbnail: { size: [ 70,70 ], mode: outbound }
    large_thumb:
      quality: 100
      filters:
        auto_rotate: ~
        thumbnail: { size: [ 200,200 ], mode: outbound }
  loaders:
    default:
      filesystem:
        locator: filesystem_insecure # this allows to follow symlinks outside the public directory