version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:10.3.35
    environment:
      MARIADB_DATABASE: connect
      MARIADB_USER: symfony
      MARIADB_PASSWORD: ChangeMe!
      MARIADB_ROOT_PASSWORD: ChangeMe!
    volumes:
      - connect-data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###
  ldap:
    image: bitnami/openldap:latest
    environment:
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: ChangeMe!
      LDAP_USERS: username
      LDAP_PASSWORDS: ChangeMe!

volumes:
###> doctrine/doctrine-bundle ###
  connect-data:
###< doctrine/doctrine-bundle ###
