version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3306"
###< doctrine/doctrine-bundle ###
  ldap:
    ports:
      - "1389"
    labels:
      com.symfony.server.service_prefix: 'LDAP'

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
###< symfony/mailer ###
