version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:10.3.35
    environment:
      MARIADB_DATABASE: connect
      MARIADB_USER: symfony
      MARIADB_PASSWORD: ChangeMe!
      MARIADB_ROOT_PASSWORD: ChangeMe!
    volumes:
      - db:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  db:
###< doctrine/doctrine-bundle ###
