version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "127.0.0.1:18306:3306"
###< doctrine/doctrine-bundle ###
  ldap:
    ports:
      - "127.0.0.1::1389"
    labels:
      com.symfony.server.service_prefix: 'LDAP'

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["127.0.0.1::1025", "127.0.0.1::1080"]
###< symfony/mailer ###
