# Defines an admin user that will be created
initialize-admin-user:
  username: username
  first-name: User
  last-name: Name

# Defines an SQL file with initial settings that will be imported
import-sql: filename.sql