<?php
/*
 * Copyright (c) 2023 University of Illinois Board of Trustees.
 * All rights reserved.
 */

namespace App\Security;

use Psr\Log\LoggerInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Http\Authentication\DefaultAuthenticationSuccessHandler;
use Symfony\Component\Security\Http\HttpUtils;

class SkipAPISuccessHandler extends DefaultAuthenticationSuccessHandler
{
    public function __construct(private readonly RouterInterface $router, HttpUtils $httpUtils, array $options = [], LoggerInterface $logger = null)
    {
        parent::__construct($httpUtils, $options, $logger);
    }

    public function onAuthenticationSuccess(Request $request, TokenInterface $token): ?Response
    {
        if(str_contains($this->determineTargetUrl($request), '/api/')){
            return new RedirectResponse($this->router->generate('default'));
        }
        return parent::onAuthenticationSuccess($request, $token); // TODO: Change the autogenerated stub
    }
}